repos:
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.21.0
    hooks:
      - id: eslint
        types: [file]
        types_or: [ts, tsx, javascript]
        args: [--fix]
        additional_dependencies:
          - eslint@8.56.0
          - globals@13.24.0
          - typescript@5.3.3
          - "@typescript-eslint/eslint-plugin@6.19.0"
          - "@typescript-eslint/parser@6.19.0"
